apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: startup-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLables:
      app:labels:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      conatainers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort:3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
            name: startup-config
            key: MYSQL_DATABASE
          volumeMounts:
          - name: mysql-pv-storage
            mounthPath: /var/lib/mysql
            subpath: mysql-data
        volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        