apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: startup-namespace
spec:
 accessModes:
    - ReadWriteOnce
 resources:
    requests:
      storage: 10Gi
 storageClassName: standard