apiVersion: v1
kind: Service
metadata:
  name: startup-service
  namespace: startup-namespace
spec:
  type: LoadBalancer
  selector:
    app: startup-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

