apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: startup-service
  namespace: startup-namespace
  labels:
    app: startup
spec:
  selector:
    app: startup-deploy
  ports:
  - port: 8080
    targetPort: 8080
